### ISSUE TITLE
irregular time series forecasting,can u give a demo script load local csv data including multivarite time series?

### ISSUE THREAD

**Issue by luoolu** [WenjieDu/BrewPOTS#11]
Didn’t understand the online notebook use online physionet2012_dataset

**Comment by WenjieDu** [comment]
Hi there 👋,

Thank you so much for your attention to PyPOTS and BrewPOTS! You can follow me on GitHub to receive the latest news of PyPOTS. If you find PyPOTS and BrewPOTS helpful to your work, please star our repositories. Your star is your recognition, which can help more people notice PyPOTS and grow PyPOTS community. It matters and is definitely a kind of contribution to the community.

I have received your message and will respond ASAP. Thank you for your patience! 😃

Best,
Wenjie

**Comment by WenjieDu** [comment]
Hi @luoolu, could you please make it more clear that which steps in the notebook confuse you? And what kind of problem that you're trying to solve with PyPOTS?

**Comment by luoolu** [comment]
Mainly how to load my own dataFrame for testing,confusied how the data organized with the notebook "physionet2012_dataset["n_features"]"

**Comment by WenjieDu** [comment]
You may need to refer to this function 

https://github.com/WenjieDu/PyPOTS/blob/cf9b627b332e4b9a6b1c852a8c6a3bf2ae73cd29/pypots/data/generating.py#L329-L435

**Comment by luoolu** [comment]
can u give a demo,load local csv file to forecastting future data points?
loal csv like below:
Date, c1,c2,c3,c4,c5
2023/10/1, 1,2,3,4,5
2023/10/2, 6,7,8,9,10
2023/10/3, 11,12,13,14,15
......
