### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by LLL-HLL** [WenjieDu/BrewPOTS#13]
print(physionet2012_dataset.keys())
输出是：
dict_keys(['n_classes', 'n_steps', 'n_features', 'train_X', 'train_y', 'train_ICUType', 'val_X', 'val_y', 'val_ICUType', 'test_X', 'test_y', 'test_ICUType', 'scaler', 'val_X_ori', 'test_X_ori', 'test_X_indicating_mask'])

与下文代码不匹配
# Assemble the datasets for training, validating, and testing.

dataset_for_training = {
    "X": physionet2012_dataset['train_X'],
}

dataset_for_validating = {
    "X": physionet2012_dataset['val_X'],
    "X_intact": physionet2012_dataset['val_X_intact'],
    "indicating_mask": physionet2012_dataset['val_X_indicating_mask'],
}

dataset_for_testing = {
    "X": physionet2012_dataset['test_X'],
}

**Comment by WenjieDu** [comment]
Hi there 👋,

Thank you so much for your attention to PyPOTS and BrewPOTS! You can follow me on GitHub to receive the latest news of PyPOTS. If you find PyPOTS and BrewPOTS helpful to your work, please star our repositories. Your star is your recognition, which can help more people notice PyPOTS and grow PyPOTS community. It matters and is definitely a kind of contribution to the community.

I have received your message and will respond ASAP. Thank you for your patience! 😃

Best,
Wenjie
