### ISSUE TITLE
gpu version

### ISSUE THREAD

**Issue by ShadowIterator** [WenjieDu/BrewPOTS#7]
is there way to use gpu for fitting and inferencing?

**Comment by WenjieDu** [comment]
Hi there 👋,

Thank you so much for your attention to PyPOTS! If you find PyPOTS helpful to your work, please star⭐️ [PyPOTS](https://github.com/WenjieDu/PyPOTS/) and this BrewPOTS repository. Your star is your recognition, which can help more people notice PyPOTS and grow PyPOTS community. It matters and is definitely a kind of contribution to the community.

I have received your message and will respond ASAP. Thank you for your patience! 😃

Best,
Wenjie
